services:
  backend:
    image: safetycar-dev-backend:latest
    container_name: safetycar-dev-backend
    networks:
      - backend-network
    # restart: unless-stopped
    expose:
      - "8080"
      - "5432/udp" # udp

networks:
  backend-network:
    external: true